### ISSUE TITLE
GetAllUserAsync [Not Found]

### ISSUE THREAD

**Issue by belizar** [auth0/auth0.net#261] opened 2019-05-15 17:49 UTC
### Description
I want to get all users.

### Prerequisites

[ x] I have checked the [documentation for this library](https://auth0.github.io/auth0.net/).

[ x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[x ] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.net/issues) and [PRs](https://github.com/auth0/auth0.net/pulls).

[x ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[ x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.NET used: v6.1.0
- Version of .NET used: .netcore 2.2

### Reproduction
Try to get all users.

![image](https://user-images.githubusercontent.com/37871475/57797172-38f8d080-7720-11e9-81d7-8e59c9d0cee3.png)

![image](https://user-images.githubusercontent.com/37871475/57797309-85441080-7720-11e9-8156-113c062bc68e.png)

**Comment by damieng** [comment] 2019-05-20 17:14
I'm running one of the integration tests here that runs the exact same call and not seeing this error:

![image](https://user-images.githubusercontent.com/118951/58039549-efc1cb80-7ae7-11e9-9192-07b6aa5e0597.png)

Are you going through a proxy?
Do any of the other APIs work?

**Comment by belizar** [comment] 2019-05-21 12:49
I dont use a proxy and the other APIs works correctly

**Comment by damieng** [comment] 2019-05-22 01:42
I've not been able to reproduce this issue.

**Comment by belizar** [comment] 2019-05-22 19:44
In your code, Where you set the auth0 endpoint url? I will test it by postman.

**Comment by damieng** [comment] 2019-05-22 19:49
It's set to our tenant setup for the SDK management API team that our integration tests use.  It won't work for you without a valid api key for our tenant which I can't give out for security reasons.

Are you able to see what URL your test is hitting and try that in postman?

**Comment by belizar** [comment] 2019-05-22 19:53
I tried it again with other APIs and now none works, I think the problem is I use a not valid api key. I will check it. 

Thank you for your quickly response.

**Comment by damieng** [comment] 2019-05-23 20:59
Closing issue, re-open/respond if it turns out not to be a key problem.

**Closed by damieng** 2019-05-23 20:59 UTC
