### ISSUE TITLE
Auth0.ManagementAPI Nuget: UserClient GetPermissionsAsync call does not return paging information

### ISSUE THREAD

**Issue by mohit0316** [auth0/auth0.net#284] opened 2019-08-16 14:31 UTC
### Description

The call to `Users.GetPermissionsAsync` is returning the correct results, but is missing the paging information in the response. The Paging object on the `IPagedList<T>` is coming back as `null`. I have tested this in versions **6.2.0, 6.3.0 and the latest 6.4.0** of the `Auth0.ManagementApi` nuget package. Because of the missing information about pagination, we are unable to display the results with paging on our end currently. 

Please see below screenshot for the response in code: 

![GetPermissionsAsync_Bug](https://user-images.githubusercontent.com/3439983/63174752-98f95e80-c010-11e9-9cfe-b453189c9903.png)

### Environment

Please provide the following:

- Version of Auth0.NET used: **Auth0.ManagementApi version 6.4.0**
- Version of .NET used: **.NET Core 2.1**
- Any other relevant environmental versions: No
- Additional libraries that might be affecting your instance: No

Prerequisites
 - [x] I have checked the documentation for this library.

 - [x] I have checked the Auth0 Community for related posts.

 - [x] I have checked for related or duplicate Issues and PRs.

 - [x] I have read the Auth0 general contribution guidelines.

  - [x] I have read the Auth0 Code of Conduct.

### Reproduction

This error can be re-produced every-time we make a call to the GetPermissionsAsync endpoint on the UsersClient in the package. We are using access tokens generated pro-grammatically. 

I was also able to re-produce this issue using the API explorer application on the Auth0 management Docs portal: https://auth0.com/docs/api/management/v2#!/Users/get_permissions

In fact, on the portal above, the results don't even come back, it's currently returning a 400 with a valid access token saying invalid query string parameters (I did not use any query string params in the request). 

Please see below screenshot:

![GetPermissionsAsync_Auth0](https://user-images.githubusercontent.com/3439983/63173946-f2f92480-c00e-11e9-89f0-7781a896d239.PNG)

**Comment by damieng** [comment] 2019-08-19 03:09
Duplicate of  #282

**Comment by mohit0316** [comment] 2019-08-19 03:17
@damieng Please note if you're closing this as a duplicate - The problem I was referring to is in the `UserClient` GetPermissionsAsync. The issue you referenced above is for RolesClient they are two different endpoints I think. Thanks.

**Comment by damieng** [comment] 2019-08-19 03:20
Sorry, you're absolutely right. Both RolesClient and UsersClient have a GetPermissionsAsync.  Fix is likely the same but will require a PR.  Reopened.

**Comment by damieng** [comment] 2019-08-19 09:35
Thanks, will go out in the next release shortly.

**Closed by damieng** 2019-08-19 09:35 UTC

**Comment by mohit0316** [comment] 2019-08-21 16:15
@damieng The latest version 6.5.0 is returning `null` for `UsersClient.GetUserPermissionsAsync` altogether now, let alone `Paging`. Seems a problem on the API side the client seems to be sending the request correctly.

**Comment by damieng** [comment] 2019-08-21 16:25
Thanks, I'll investigate further and raise any necessary escalation with the correct server team.

**Comment by damieng** [comment] 2019-08-21 16:30
Hmm, the server side appears to be working correctly for me.  I'll dig into what's gone awry in the client later today.

**Comment by damieng** [comment] 2019-08-21 17:01
https://github.com/auth0/auth0.net/pull/287

**Comment by mohit0316** [comment] 2019-08-21 17:03
Thanks @damieng i noticed the issue just now too it was being returned in the wrong property.
