### ISSUE TITLE
ManagementApiClient does not implement an interface

### ISSUE THREAD

**Issue by benprime** [auth0/auth0.net#280] opened 2019-08-07 17:34 UTC
### Description

ManagementApiClient does not implement an interface and therefore is difficult to mock when unit testing code that utilizes it.

AuthenticationApiClient implements an interface, but ManagementApiClient does not.

### Prerequisites

- [x] I have checked the [documentation for this library](https://auth0.github.io/auth0.net/).

- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.net/issues) and [PRs](https://github.com/auth0/auth0.net/pulls).

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.NET used: 6.4.0
- Version of .NET used: .Net Core 2.1

**Comment by damieng** [comment] 2019-08-07 20:27
Duplicate of #250

**Closed by damieng** 2019-08-07 20:27 UTC
